In [2]:
import numpy as np

## Aşağıdaki arr1 arrayinin orta satırını ve son sütunu seçin:

In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr1[1,2]

6

## Arrayin son satırını ters çevirerek seçin:

In [7]:
arr1[2,::-1]

array([9, 8, 7])

## Arrayin köşegen elemanlarını seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

In [10]:
arr1[(1,)()]

array([[1, 3],
       [7, 9]])

## Arrayin alt üçgenini seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

## Arrayin üst üçgenini seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

## Arrayin elemanlarını rastgele karıştırarak seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

## Aşağıdaki arr2D dizisini, 2. satırını arr1D dizisi ile toplayacak şekilde update edin.:

In [8]:
arr2D = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr1D = np.array([10, 20, 30])

display(arr2D)
display(arr1D)

array([[1, 2, 3],
       [4, 5, 6]])

array([10, 20, 30])

## Aşağıdaki arr2 arrayinin satırlarını toplayarak seçin:

In [17]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Arrayin 3. satırındaki en büyük ve en küçük elemanları seçin:

## Aşağıdaki arr3 arrayinin 5'ten küçük elemanlarını olduğu gibi, diğer elemanları 10 ile çarparak getirin:

**Derste görülenlere ilave araştırma gerektirebilir.**

In [61]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Aşağıdaki arr4 array'inin 1. ve 3. sütunlarındaki 5'ten büyük elemanlarını olduğu gibi, bu sütunların diğer elemanlarını 0 olarak getirin:
**Derste görülenlere ilave araştırma gerektirebilir.**

In [64]:
arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Arrayin 1. ve 4. sütunlarındaki 10'dan büyük ve eşit elemanları "büyük", bu sütunların diğer elemanlarını "küçük" olarak değiştirin:

**Derste görülenlere ilave araştırma gerektirebilir.**