# **Import Numpy Library**

In [1]:
import numpy as np

**https://www.w3resource.com/python-exercises/numpy/index-array.php**
- Numpy Questions: 4, 8, 9, 10, 12, 14, 19

**4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.**
<br>[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<br>Update sixth value to 11
<br>[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
print("Update sixth value to 11")

x[6] = 11
print(x)

Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


**8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.**
![image-4.png](attachment:image-4.png)

In [4]:
x = np.ones((5,5))
print("Original array:")
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**9. Write a NumPy program to add a border (filled with 0's) around an existing array.**
![image-2.png](attachment:image-2.png)

In [6]:
x = np.ones((3,3))
print("Original array:")
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.**
![image.png](attachment:image.png)

In [8]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x

Checkerboard pattern:


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [10]:
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**12. Write a NumPy program to append values to the end of an array.**
![image-2.png](attachment:image-2.png)

In [11]:
x = [10, 20, 30]
print("Original array:")
print(x)

Original array:
[10, 20, 30]


In [12]:
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


**14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.**
![image.png](attachment:image.png)

In [13]:
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]


In [14]:
print("Values in  Centigrade degrees:")
print(5*F/9 - 5*32/9)

Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


**19. Write a NumPy program to get the unique elements of an array.**
![image.png](attachment:image.png)

In [15]:
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)

Original array:
[10 10 20 20 30 30]


In [16]:
print("Unique elements of the above array:")
print(np.unique(x))

Unique elements of the above array:
[10 20 30]


In [17]:
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)

Original array:
[[1 1]
 [2 3]]


In [18]:
print("Unique elements of the above array:")
print(np.unique(x))

Unique elements of the above array:
[1 2 3]


# **import Pandas Library**

In [19]:
import pandas as pd

**https://www.w3resource.com/python-exercises/pandas/index-data-series.php**
- Pandas Questions: 2, 3, 5, 6, 13

**2. Write a Pandas program to convert a Pandas module Series to Python list and it's type.**

In [20]:
list_1 = [2, 4, 6, 8, 10]

In [21]:
# Convert the Python list to a Pandas Series
ds = pd.Series(list_1)
print("Pandas Series and type")
print(ds)
print(type(ds))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>


In [22]:
# Convert the Pandas Series to Python list
print(ds.tolist())
print(type(ds.tolist()))

[2, 4, 6, 8, 10]
<class 'list'>


**3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.**

In [23]:
list1 = [2, 4, 6, 8, 10]
list2 = [1, 3, 5, 7, 9]

In [24]:
# Create two Pandas series with these lists
ds1 = pd.Series(list1)
ds2 = pd.Series(list2)

In [25]:
ds = ds1 + ds2
print("Add two Series:")
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64


In [26]:
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)

Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64


In [27]:
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)

Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64


In [28]:
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


**5. Write a Pandas program to convert a dictionary to a Pandas series.**

In [29]:
keys=['a','b','c','d','e']
values = [100, 200, 300, 400, 800]

In [30]:
# Create a dictionary from keys and values
d1={keys[i]:values[i] for i in range(len(keys))}
print("Original dictionary:")
print(d1)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}


In [31]:
# Convert the dictionary to a Pandas series
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


**6. Write a Pandas program to convert a NumPy array to a Pandas series.**

In [32]:
# Original Data : [10, 20, 30, 40, 50]
# Create a numpy array with this data

np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)

NumPy array:
[10 20 30 40 50]


In [33]:
# Convert a NumPy array to this Pandas series.

new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int32


**12. Write a Pandas program to add some data to an existing Series.**|

In [34]:
# Original Data : ['100', '200', 'python', '300.12', '400']
# Built a pandas Series with this data

s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [36]:
new_s = pd.concat([s, pd.Series(['500', 'php'])])

print(new_s)

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


**13. Write a Pandas program to create a subset of a given series based on value and condition.**

In [37]:
# Original Data : [0,1,2,3,4,5,6,7,8,9,10]
# Built a pandas Series with this data

s = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64


In [38]:
# Create a new series with data with a value less than 6

print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)


Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
